### PR TITLE
Add luminance, contrast and darkness values

### PR DESCRIPTION
**Pull request by darekkay**
Add plugins to calculate the luminance, contrast ratio and darkness values for colors.
This code is based on the [color](https://github.com/Qix-/color/blob/master/index.js) library's code, which unfortunately is not available for browser usage.

### CODE REVIEW

**Comment by darekkay** [comment]
This may close #27, although it only returns "dark" or "light", not a decimal brightness value. But it's the same formula as used by the [colourBrightness](https://github.com/jamiebrittain/colourBrightness.js) jQuery plugin.

**Comment by darekkay** [comment]
Sure, I removed the generated files.

**Comment by Munter** [comment]
I wanted to push out a minor version release, but I can't run the build on my windows machine :'(

**Comment by papandreou** [comment]
Published 3.1.0.

Thanks again, @darekkay!

**Comment by darekkay** [comment]
Thanks for the quick response 😄 

@Munter I've had the same problem. I changed the `one-color` and `one-color-all` tasks from `... .js; rm OUT.*` to `... .js && rm OUT.*`, so it could be run at least on Git Bash (cmd still failed). Use something like [rimraf](https://www.npmjs.com/package/rimraf) to make it truly OS-independent. 

Another issue was that the build task uses CRLF instead of LF on Windows, so you might not want to publish a Windows-built version anyway.

**Pull request merged**
