### PR TITLE
Support #rrggbbaa and #rgba

### PR DESCRIPTION
**Pull request by papandreou**

### CODE REVIEW

**Comment by Munter** [comment]
This will present a problem for us. The current [`color.hexa()`](https://github.com/One-com/one-color/blob/master/lib/color.js#L240-L243)-method returns `#AARRGGBB`, so the alpha channel in the first position.
Android uses this notation. 

I remember us having discussions about supporting a 4 channel hex in the parser, but ultimately dropped it because there are conflicting standards on whether the alpha channel goes first or last.

Locking it in one position potentially excludes the opposite user group :(

What to do?

**Comment by Munter** [comment]
The discussion in the ["added threejs format" PR](https://github.com/One-com/one-color/pull/16#issuecomment-14143135) adds a bit more depth to this. We actually decided back then to remove support for formats that might be ambiguous.

Is it time to revisit that decision?

**Comment by Munter** [comment]
The biggest annoyance I have is that anyone can add a plugin for whatever output they desire. But the parser doesn't really allow for extensions at the moment, so there is no way an outsider who just wants a specific format can add it to the parser

**Comment by papandreou** [comment]
Ah, I had totally forgotten about that Android thing. This just seemed like 15 minutes of fun coding. Didn't check whether that new color spec was a candidate recommendation or whatever yet, but yeah, I think it's time to revisit the decision.

**Comment by jpdevries** [comment]
Oh the joys of cross browser incompatibilities and bleeding edge technology. 

I've got a situation where a `fill` could come in as a normal hex or an alpha hex and here is how I am working around this for now

```js

const hexToRgba = require('hex-and-rgba').hexToRgba;
const rgbaToHex = require('hex-and-rgba').rgbaToHex;

try {
  fill = hex = color(fill.toString().replace('0x','#')).cssa();
} catch(e) {
  fill = hexToRgba(fill.replace('0x','#'));
  opacity = fill[3];
  fill = `rgba(${fill[0]},${fill[1]},${fill[2]},${fill[3]})`;
}
```

**Comment by papandreou** [comment]
I just noticed this on my list of open pull requests. CSS Color Module Level 4 is still a working draft, so I guess we can't really move it forward still. Standards are slow :)

**Comment by cakeinpanic** [comment]
Browsers you notation where Alhpa comes as last 2 symbols. Can't use this lib because of it :(

**Comment by papandreou** [comment]
> Browsers you notation where Alhpa comes as last 2 symbols. Can't use this lib because of it :(

:cry:

I've brought this branch back to life and changed `.hexa()` to return `#rrggbbaa`. I think we should get it merged and do a new major release. Any objections, @Munter? :hugs:

**Review by Munter — APPROVED** [review]
Agreed. I think the CSS color module is what we want to follow.

Major version bump it is

**Comment by papandreou** [comment]
Released in 4.0.0

**Pull request merged**
